name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check if 'actions-runner' directory exists
      run: |
        if [ ! -d "actions-runner" ]; then
          mkdir actions-runner
        fi
      continue-on-error: true

    - name: Change to 'actions-runner' directory
      run: cd actions-runner

    - name: Install Dependencies
      run: npm i

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test
